### ISSUE TITLE
Documentation for flows is out dated?

### ISSUE THREAD

**Issue by tstankevicius** [yukatan/commangular#10]
Hello,

in CommAngular docs for command flows section you define the flow examples as such:

.add('Command1') // returns "result1"
.add($commangularProvider.asFlow()
   // Link to sequence
      .link('result1 == true').to(sequence)

At least for version 0.8.0 it does not work! Commangular does not understand primitive variables returned from command1. I must be an object with some property inside. So...

.add('Command1') // returns "result1"
.add($commangularProvider.asFlow()
   // Link to sequence
      .link('result1.value == true').to(sequence)

spent several hours working this out...

**Comment by yukatan** [comment]
Hi,

The flow feature in commangular is using the $interpolate service from Angular and using the command context as context. There is a test in the test folder for version 0.8.0 testing exactly what you are saying.

check it out at test folder/groups/flow-with-numbers-test.js

it works so.. maybe you have any other error, let me know
