### ISSUE TITLE
The relevance of onResult / onError

### ISSUE THREAD

**Issue by sebastian-zarzycki** [yukatan/commangular#5]
Hi, long time Flex/Parsley developer here. Delighted to have found out about Commangular. 

However, after some tests, I'm kind of confused as to how it work. My main problem lies with asynchronous commands. As far as I could tell, currently the whole framework revolves around returning the value from execute() in command. Why? The thing is, that if you have synchronous operations, then you probably don't need to use any external framework, you can just call some functions one after the other. The great power of framework should be handing async Commands. Unless I'm mistaken, this is kind of flawed right now, because the framework assumes that whenever the promise is returned, the command is complete (?), it just applies some additional logic in the background to wait for the promise when commands are processed as sequence. Currently, I'm just receiving a promise in onResult and I have to unpack it manually, but this is done long after the command is deemed to be completed, so kills the point of doing so at all.

If I'm returning a promise, I would expect that it gets unpacked and resolved as a result parameter of onResult, and only after returning something from onResult the command would actually complete - because most of the logic will actually be there, and from there the result matters, not just a result of an async call (that's how Parsley works). When I intercept a Command with @After, I can see that it gets called whenever something is returned from execute and not when something is returned from onResult. So, either I'm using this wrong, or these limitations actually exist - and in current form, it just nullifies the sense of using the framework altogether. Am I doing something wrong here / will it be changed in near future? I'm happy to help/test.

**Comment by sebastian-zarzycki** [comment]
Any new developments? We're far into 2015 now :)

**Comment by yukatan** [comment]
clone the branch commangular-fixes-5. The result from onResult is now the result from the command. I've added some test but check if it works.

Im working on change the @After behaviour

**Comment by sebastian-zarzycki** [comment]
Great news! I'll wait patiently for the release, but happy to test any beta builds.

**Comment by yukatan** [comment]
Check the last release 0.9.0
The @After interceptor now is executed after the onResult command method. There is a new @AfterExecution interceptor that is executed before the onResult.

The command result is the result from the onResult method if it exits.

Let me now if you find any problem or bug

**Comment by sebastian-zarzycki** [comment]
Works great - thanks!

**Comment by yukatan** [comment]
Perfect :) then I close the issue
